name: OpenWrt

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Check disk space
        run: df -h

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 lib32gcc-s1 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Clear runner logs
        run: |
          sudo truncate -s 0 /home/runner/actions-runner/cached/_diag/*.log
          df -h

      - name: Download lede
        run: |
          git clone --depth 1 https://github.com/coolsnowwolf/lede
          cp .config ./lede/.config
          mv ./lede/* ./

      - name: Install Helloword
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 

      - name: Install OpenClash
        run: |
          mkdir package/luci-app-openclash
          cd package/luci-app-openclash
          git init
          git remote add -f origin https://github.com/vernesong/OpenClash.git
          git config core.sparsecheckout true
          echo "luci-app-openclash" >> .git/info/sparse-checkout
          git pull --depth 1 origin master
          git branch --set-upstream-to=origin/master master
          pushd luci-app-openclash/tools/po2lmo
          make && sudo make install
          popd

      - name: Update feeds
        run: |
          ./scripts/feeds update -a || { echo "Feeds update failed"; exit 1; }
          ./scripts/feeds install -a || { echo "Feeds install failed"; exit 1; }

      - name: Custom configure file
        run: |
          make defconfig
          if [ ! -f .config ]; then echo "Config file missing"; exit 1; fi

      - name: Check disk space before download
        run: df -h

      - name: Download package source code
        run: |
          for i in {1..3}; do make download -j8 && break || { echo "Retry $i failed"; sleep 5; }; done
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Clean up disk space before compile
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          sudo rm -rf dl/*.tar.gz dl/*.zip dl/*.tgz
          find . -name "*.o" -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          echo -e "1 thread build."
          make -j1

      - name: Clean up after compile
        run: |
          make clean
          df -h

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: bin/targets/*/*.bin
